require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'node_modules/**/*'
    - 'gemfiles/**/*'
    - 'vendor/**/*'
    - lib/apollo-federation/tracing/proto/apollo_pb.rb

Layout/LineLength:
  Max: 120

#
# We prefer trailing commas so that the git diff is reduced when adding elements
#
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/IfUnlessModifier:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Naming/FileName:
  Exclude:
    - 'lib/apollo-federation.rb'
    - 'graphql-1.9.gemfile'

RSpec/ExampleLength:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/RepeatedExampleGroupDescription:
  Enabled: false
RSpec/SpecFilePathFormat:
  CustomTransform:
    ApolloFederation: apollo-federation

# Disabled so we can support Ruby 2.2
# Rubocop only supports >= 2.3
Gemspec/RequiredRubyVersion:
  Enabled: false
